/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as UsersRouteImport } from "./routes/users";
import { Route as StoresRouteImport } from "./routes/stores";
import { Route as ServicesRouteImport } from "./routes/services";
import { Route as ProductsRouteImport } from "./routes/products";
import { Route as PaymentMethodsRouteImport } from "./routes/payment-methods";
import { Route as OrdersRouteImport } from "./routes/orders";
import { Route as CustomersRouteImport } from "./routes/customers";
import { Route as CategoriesRouteImport } from "./routes/categories";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";

const UsersRoute = UsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => rootRouteImport,
} as any);
const StoresRoute = StoresRouteImport.update({
  id: "/stores",
  path: "/stores",
  getParentRoute: () => rootRouteImport,
} as any);
const ServicesRoute = ServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsRoute = ProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => rootRouteImport,
} as any);
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: "/payment-methods",
  path: "/payment-methods",
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersRoute = OrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => rootRouteImport,
} as any);
const CustomersRoute = CustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesRoute = CategoriesRouteImport.update({
  id: "/categories",
  path: "/categories",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/categories": typeof CategoriesRoute;
  "/customers": typeof CustomersRoute;
  "/orders": typeof OrdersRoute;
  "/payment-methods": typeof PaymentMethodsRoute;
  "/products": typeof ProductsRoute;
  "/services": typeof ServicesRoute;
  "/stores": typeof StoresRoute;
  "/users": typeof UsersRoute;
  "/auth/login": typeof AuthLoginRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/categories": typeof CategoriesRoute;
  "/customers": typeof CustomersRoute;
  "/orders": typeof OrdersRoute;
  "/payment-methods": typeof PaymentMethodsRoute;
  "/products": typeof ProductsRoute;
  "/services": typeof ServicesRoute;
  "/stores": typeof StoresRoute;
  "/users": typeof UsersRoute;
  "/auth/login": typeof AuthLoginRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/categories": typeof CategoriesRoute;
  "/customers": typeof CustomersRoute;
  "/orders": typeof OrdersRoute;
  "/payment-methods": typeof PaymentMethodsRoute;
  "/products": typeof ProductsRoute;
  "/services": typeof ServicesRoute;
  "/stores": typeof StoresRoute;
  "/users": typeof UsersRoute;
  "/auth/login": typeof AuthLoginRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/categories"
    | "/customers"
    | "/orders"
    | "/payment-methods"
    | "/products"
    | "/services"
    | "/stores"
    | "/users"
    | "/auth/login";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/categories"
    | "/customers"
    | "/orders"
    | "/payment-methods"
    | "/products"
    | "/services"
    | "/stores"
    | "/users"
    | "/auth/login";
  id:
    | "__root__"
    | "/"
    | "/categories"
    | "/customers"
    | "/orders"
    | "/payment-methods"
    | "/products"
    | "/services"
    | "/stores"
    | "/users"
    | "/auth/login";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CategoriesRoute: typeof CategoriesRoute;
  CustomersRoute: typeof CustomersRoute;
  OrdersRoute: typeof OrdersRoute;
  PaymentMethodsRoute: typeof PaymentMethodsRoute;
  ProductsRoute: typeof ProductsRoute;
  ServicesRoute: typeof ServicesRoute;
  StoresRoute: typeof StoresRoute;
  UsersRoute: typeof UsersRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/users": {
      id: "/users";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof UsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/stores": {
      id: "/stores";
      path: "/stores";
      fullPath: "/stores";
      preLoaderRoute: typeof StoresRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products": {
      id: "/products";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof ProductsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/payment-methods": {
      id: "/payment-methods";
      path: "/payment-methods";
      fullPath: "/payment-methods";
      preLoaderRoute: typeof PaymentMethodsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders": {
      id: "/orders";
      path: "/orders";
      fullPath: "/orders";
      preLoaderRoute: typeof OrdersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/customers": {
      id: "/customers";
      path: "/customers";
      fullPath: "/customers";
      preLoaderRoute: typeof CustomersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories": {
      id: "/categories";
      path: "/categories";
      fullPath: "/categories";
      preLoaderRoute: typeof CategoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRoute,
  OrdersRoute: OrdersRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRoute,
  StoresRoute: StoresRoute,
  UsersRoute: UsersRoute,
  AuthLoginRoute: AuthLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
