/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TrackRouteImport } from "./routes/track";
import { Route as AdminRouteRouteImport } from "./routes/_admin/route";
import { Route as AdminIndexRouteImport } from "./routes/_admin/index";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AdminWorkerRouteImport } from "./routes/_admin/worker";
import { Route as AdminUsersRouteImport } from "./routes/_admin/users";
import { Route as AdminStoresRouteImport } from "./routes/_admin/stores";
import { Route as AdminServicesRouteImport } from "./routes/_admin/services";
import { Route as AdminProductsRouteImport } from "./routes/_admin/products";
import { Route as AdminPaymentMethodsRouteImport } from "./routes/_admin/payment-methods";
import { Route as AdminOrdersRouteImport } from "./routes/_admin/orders";
import { Route as AdminCustomersRouteImport } from "./routes/_admin/customers";
import { Route as AdminCategoriesRouteImport } from "./routes/_admin/categories";
import { Route as AdminCampaignsRouteImport } from "./routes/_admin/campaigns";
import { Route as AdminOrdersOrderIdRouteImport } from "./routes/_admin/orders.$orderId";

const TrackRoute = TrackRouteImport.update({
  id: "/track",
  path: "/track",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: "/_admin",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminWorkerRoute = AdminWorkerRouteImport.update({
  id: "/worker",
  path: "/worker",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: "/stores",
  path: "/stores",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: "/payment-methods",
  path: "/payment-methods",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: "/categories",
  path: "/categories",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: "/campaigns",
  path: "/campaigns",
  getParentRoute: () => AdminRouteRoute,
} as any);
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: "/$orderId",
  path: "/$orderId",
  getParentRoute: () => AdminOrdersRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AdminIndexRoute;
  "/track": typeof TrackRoute;
  "/campaigns": typeof AdminCampaignsRoute;
  "/categories": typeof AdminCategoriesRoute;
  "/customers": typeof AdminCustomersRoute;
  "/orders": typeof AdminOrdersRouteWithChildren;
  "/payment-methods": typeof AdminPaymentMethodsRoute;
  "/products": typeof AdminProductsRoute;
  "/services": typeof AdminServicesRoute;
  "/stores": typeof AdminStoresRoute;
  "/users": typeof AdminUsersRoute;
  "/worker": typeof AdminWorkerRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/orders/$orderId": typeof AdminOrdersOrderIdRoute;
}
export interface FileRoutesByTo {
  "/track": typeof TrackRoute;
  "/campaigns": typeof AdminCampaignsRoute;
  "/categories": typeof AdminCategoriesRoute;
  "/customers": typeof AdminCustomersRoute;
  "/orders": typeof AdminOrdersRouteWithChildren;
  "/payment-methods": typeof AdminPaymentMethodsRoute;
  "/products": typeof AdminProductsRoute;
  "/services": typeof AdminServicesRoute;
  "/stores": typeof AdminStoresRoute;
  "/users": typeof AdminUsersRoute;
  "/worker": typeof AdminWorkerRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/": typeof AdminIndexRoute;
  "/orders/$orderId": typeof AdminOrdersOrderIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_admin": typeof AdminRouteRouteWithChildren;
  "/track": typeof TrackRoute;
  "/_admin/campaigns": typeof AdminCampaignsRoute;
  "/_admin/categories": typeof AdminCategoriesRoute;
  "/_admin/customers": typeof AdminCustomersRoute;
  "/_admin/orders": typeof AdminOrdersRouteWithChildren;
  "/_admin/payment-methods": typeof AdminPaymentMethodsRoute;
  "/_admin/products": typeof AdminProductsRoute;
  "/_admin/services": typeof AdminServicesRoute;
  "/_admin/stores": typeof AdminStoresRoute;
  "/_admin/users": typeof AdminUsersRoute;
  "/_admin/worker": typeof AdminWorkerRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/_admin/": typeof AdminIndexRoute;
  "/_admin/orders/$orderId": typeof AdminOrdersOrderIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/track"
    | "/campaigns"
    | "/categories"
    | "/customers"
    | "/orders"
    | "/payment-methods"
    | "/products"
    | "/services"
    | "/stores"
    | "/users"
    | "/worker"
    | "/auth/login"
    | "/orders/$orderId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/track"
    | "/campaigns"
    | "/categories"
    | "/customers"
    | "/orders"
    | "/payment-methods"
    | "/products"
    | "/services"
    | "/stores"
    | "/users"
    | "/worker"
    | "/auth/login"
    | "/"
    | "/orders/$orderId";
  id:
    | "__root__"
    | "/_admin"
    | "/track"
    | "/_admin/campaigns"
    | "/_admin/categories"
    | "/_admin/customers"
    | "/_admin/orders"
    | "/_admin/payment-methods"
    | "/_admin/products"
    | "/_admin/services"
    | "/_admin/stores"
    | "/_admin/users"
    | "/_admin/worker"
    | "/auth/login"
    | "/_admin/"
    | "/_admin/orders/$orderId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren;
  TrackRoute: typeof TrackRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/track": {
      id: "/track";
      path: "/track";
      fullPath: "/track";
      preLoaderRoute: typeof TrackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin": {
      id: "/_admin";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AdminRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin/": {
      id: "/_admin/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_admin/worker": {
      id: "/_admin/worker";
      path: "/worker";
      fullPath: "/worker";
      preLoaderRoute: typeof AdminWorkerRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/users": {
      id: "/_admin/users";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof AdminUsersRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/stores": {
      id: "/_admin/stores";
      path: "/stores";
      fullPath: "/stores";
      preLoaderRoute: typeof AdminStoresRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/services": {
      id: "/_admin/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof AdminServicesRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/products": {
      id: "/_admin/products";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof AdminProductsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/payment-methods": {
      id: "/_admin/payment-methods";
      path: "/payment-methods";
      fullPath: "/payment-methods";
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/orders": {
      id: "/_admin/orders";
      path: "/orders";
      fullPath: "/orders";
      preLoaderRoute: typeof AdminOrdersRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/customers": {
      id: "/_admin/customers";
      path: "/customers";
      fullPath: "/customers";
      preLoaderRoute: typeof AdminCustomersRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/categories": {
      id: "/_admin/categories";
      path: "/categories";
      fullPath: "/categories";
      preLoaderRoute: typeof AdminCategoriesRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/campaigns": {
      id: "/_admin/campaigns";
      path: "/campaigns";
      fullPath: "/campaigns";
      preLoaderRoute: typeof AdminCampaignsRouteImport;
      parentRoute: typeof AdminRouteRoute;
    };
    "/_admin/orders/$orderId": {
      id: "/_admin/orders/$orderId";
      path: "/$orderId";
      fullPath: "/orders/$orderId";
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport;
      parentRoute: typeof AdminOrdersRoute;
    };
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute;
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
};

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
);

interface AdminRouteRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute;
  AdminCategoriesRoute: typeof AdminCategoriesRoute;
  AdminCustomersRoute: typeof AdminCustomersRoute;
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren;
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute;
  AdminProductsRoute: typeof AdminProductsRoute;
  AdminServicesRoute: typeof AdminServicesRoute;
  AdminStoresRoute: typeof AdminStoresRoute;
  AdminUsersRoute: typeof AdminUsersRoute;
  AdminWorkerRoute: typeof AdminWorkerRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkerRoute: AdminWorkerRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TrackRoute: TrackRoute,
  AuthLoginRoute: AuthLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
